version: "3"
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
#    env_file: .docker-env
    environment:
#      DATABASE_URL: 'mysql2://db'
      RAILS_ENV: 'development'
    restart: always
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    entrypoint: bash -c
    command: "rm -f tmp/pids/server.pid"
    command: |
      "bundle install && bundle exec rails s -b 0.0.0.0 -p 3000"
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
