FROM ruby:2.6.2

ENV APP_ROOT /app

WORKDIR $APP_ROOT

ENV RAILS_ENV=development
ADD Gemfile $APP_ROOT
ADD Gemfile.lock $APP_ROOT
RUN gem install bundler:2.0.2
RUN bundle lock --add-platform java
RUN bundle update --bundler
RUN bundle install && rm -rf ~/.gem
ADD . $APP_ROOT
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "development"]

