default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
development:
  <<: *default
  host: db
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
  database: hiroki_database_create 
#test:
#  <<: *default
#  database: rails_sample_development
