default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306

development:
  <<: *default
  host: db
  username: root
  password:
  database: development_db

test:
  <<: *default
  host: db 
  username: root
  password:
  database: test_db

production:
  <<: *default
  database: <%= Rails.application.credentials.db[:name] %>
  username: <%= Rails.application.credentials.db[:user] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>


